# Generated by Django 4.0.5 on 2022-06-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('player_class', models.CharField(max_length=30)),
                ('strength', models.CharField(max_length=30)),
                ('intelligence', models.CharField(max_length=30)),
                ('faith', models.CharField(max_length=30)),
                ('dexterity', models.CharField(max_length=30)),
                ('vigor', models.CharField(max_length=30)),
            ],
        ),
    ]
