# Generated by Django 4.0.5 on 2022-07-23 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chartbase', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayerForm',
            new_name='PlayerModel',
        ),
    ]
